# Generated by Django 4.0.3 on 2022-03-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
